
update-dist:
	npm run html-dist

.PHONY: update-dist


lint:
	npm run tsc-check

.PHONY: lint

index-entries-json: 
	npm run make-index-map >index-entries.json

.PHONY: index-entries-json

# vi: se ts=4 sw=4 noet:
